version: '3'
services:
  app:
    build: ./app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app/